# Generated by Django 4.2.3 on 2023-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_rename_description_productimage_alt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(blank=True),
        ),
    ]
