# Generated by Django 4.2.3 on 2023-07-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
