# Generated by Django 4.2.3 on 2023-07-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopapp.product",
            ),
            preserve_default=False,
        ),
    ]
