# Generated by Django 4.2.3 on 2023-07-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="shopapp.product",
            ),
        ),
    ]
