# Generated by Django 4.2 on 2023-08-09 17:56

import api.models
import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_categoryimage_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["alt"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="api.category",
                verbose_name="Parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="alt",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="api.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="src",
            field=models.ImageField(
                upload_to=api.models.category_image_directory_path, verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="api.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date of creation"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(default=False, verbose_name="Free delivery"),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(blank=True, verbose_name="Full description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="products",
                through="api.ProductTag",
                to="api.tag",
                verbose_name="Tag",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(
                upload_to=api.models.product_images_directory_path, verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.tag",
                verbose_name="Tag",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullName",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Full name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.",
                        regex="^\\+?1?\\d{11}$",
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="profileavatar",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="api.profile",
                verbose_name="User profile",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.CharField(max_length=191, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date of creation"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="api.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Product rate",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, verbose_name="Review text"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Parameter"),
        ),
        migrations.AlterField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="api.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
