# Generated by Django 4.2 on 2023-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_productimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False, verbose_name="Limited edition"),
        ),
    ]
