# Generated by Django 4.2 on 2023-08-15 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_order_alter_basket_options_alter_basketitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
