# Generated by Django 4.2 on 2023-08-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="api.OrderItem",
                to="api.product",
                verbose_name="Products",
            ),
        ),
    ]
